### PR TITLE
update slider styling

### LINKED ISSUE #40: Update UI elements: select option & slider
Currently, these two elements are not yet correctly styled:
image

## Slider

- [ ] Update thumb color to holon-blue-500
- [ ] Add thumb border 
- [ ] Add dropshadow

## Select option
- [  ] Add select icon (cross or check mark)

### PR DESCRIPTION
**Pull request by thesethtruth**
closes #40

### CODE REVIEW

**Comment by thesethtruth** [comment]
Tested on Edge and Firefox: works with sliderthumb border.
image

Testest on Chrome: sliderhtumb border does not work (also not an existing property according to MDN)
image

**Comment by MariaBee3** [comment]
Picture5

Disabled style and check mark as select icon

**Comment by thesethtruth** [comment]
Tested in Firefox: 
- [ ] Transparency issue with checkboxes
- [ ] Disabled state does change the thumbcolor

image

**Comment by MariaBee3** [comment]
Picture1

Fixed issues in Firefox.

**Comment by pascalalferink** [comment]
Checkboxes and sliders have been succesfully reviewed.
As you can see in the screenshot @MariaBee3 submitted, the borders/shadows of the inputs besides the sliders are blue instead of gray. I have changed it.

Disabled version
image

 Open version:
image

**Pull request merged**
