### PR TITLE
11 developers use the same python formatting and linting in their ide

### PR DESCRIPTION
**Pull request by mattijsstam**

### CODE REVIEW

**Comment by mattijsstam** [comment]
- [ ] write documentation in README

**Review by antw — APPROVED** [review]
Looks good! The devcontainer builds and launches without any issues.

My only minor gripe is that running `git commit` within the devcontainer fails for me due to Vim not being available (I use it for commit messages and not much else). How do you have your Git editor configured for use in a container?

```
$ git config core.editor
vim +star +1 -c redraw
```

I get an error from the backend when the Next app tries to reach /calculation/ (AnyLogic is return 400 Bad Request). However, the same thing happens on the main branch so I'm assuming it's unrelated to anything in this PR. I think it might be because I don't have an AnyLogic API key?

Either way, I think we can merge this.

<details>
<summary><strong>Backend exception... </strong></summary>

```
Internal Server Error: /calculation/
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/anylogiccloudclient/client/http_client.py", line 21, in api_request
    response = urllib.request.urlopen(request)
  File "/usr/local/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.10/urllib/request.py", line 525, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.10/urllib/request.py", line 634, in http_response
    response = self.parent.error(
  File "/usr/local/lib/python3.10/urllib/request.py", line 563, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.10/urllib/request.py", line 643, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: Bad Request

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/generic/base.py", line 84, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/rest_framework/decorators.py", line 50, in handler
    return func(*args, **kwargs)
  File "/workspace/backend/holon/views.py", line 44, in calculationView
    results = handle_request(request.data)
  File "/workspace/backend/holon/anylogic.py", line 86, in handle_request
    model = client.get_model_by_name("Holon buurt model")
  File "/usr/local/lib/python3.10/site-packages/anylogiccloudclient/client/cloud_client.py", line 34, in get_model_by_name
    response = self._http_client.api_request("models/name/" + name)
  File "/usr/local/lib/python3.10/site-packages/anylogiccloudclient/client/http_client.py", line 23, in api_request
    raise CloudError.from_json(json.loads(err.read()))
anylogiccloudclient.client.cloud_error.CloudError: ('Bad Request', 400, 'Bad Request', '/open/8.5.0/models/name/Holon%20buurt%20model')
[02/Aug/2022 14:39:56] "POST /calculation/ HTTP/1.1" 500 145273
```

</details>

**Comment by mattijsstam** [comment]
@antw the calculation exception is because there is no correct AL_API_KEY environment variable set in the .devcontainer/.env file. You can contact @thesethtruth  to receive an api key.

Regarding the git setup, I use the vscode source control to commit and write messages so I didn't have any trouble working with git inside the container. I think you should manually install vim in the devcontainer or add it to the dockerfile but because you are the only one using that I don't think that is convienent.

**Comment by antw** [comment]
> Regarding the git setup, I use the vscode source control to commit and write messages so I didn't have any trouble working with git inside the container

Thanks, I'll try that. If nothing else, I can always still use Git from outside the devcontainer. I agree that adding Vim isn't worth it since I'm the only user.

**Pull request merged**
