### PR TITLE
Ad hoc technical fixes for MVP release

### PR DESCRIPTION
**Pull request by thesethtruth**
### Before merge to **main**
- [x] Remove the statements that write the payload to json `write_payload_to_jsons(payload_dict=self.holon_payload, name=value)`

### To do
- [x] Update datamodel `mvp.py` with new model config (place defaults in a `mpv_defaults.py` file
- [x] Verify that policies are correctly implemented now and work in Anylogic

### Done
- [x] add `DIESEL_VEHICLE`  to Assets options for both factor and interactive elements @mattijsstam @thesethtruth 
- [x] Check ETM upscaling with @noracato 
- [x] Sanity on cost module (`im_sorry.py`) @Jorritvandenhouten
- [x] Update `pepe` post processing features for the `local` outputs (result from holon + postprocess)
   - [x] Sustainability (percentage)
   - [x] Selfsufficiency (import export balans)
   - [x] Net load (percentage station capacity at peakload, greater than capacity)
- [x] Connect the KPI dashboard to the backend results and test:
    - [x] Functionality of hidden sliders and elements
    - [x] Cost division between local and national (kEUR vs mld.EUR)
- [x] Implement scaling of batteries both as slider and as single select to the same range and value (as `installed_energy_grid_battery` instead of `grid_battery_on_of`)
- [x] Implement a balancing act for `ELECTRIC_VEHICLE` vs `DIESEL_TRUCK`
- [x] Parse policies from interactive sliders in `pepe.preprocessor.apply_interactive_to_payload()` (see comment below)
    - [x] Charging
    - [x] Financial
    - [x] Contracts

### CODE REVIEW

**Comment by thesethtruth** [comment]
Hi @noracato and @marliekeverweij,

We are experiencing some odd results from the upscaling through the `HOLON-ETM` module. For some reason, the results that are coming back seem to be that of an regular / unchanged 2050 scenario. I'm unsure, but it seems that the `scenario_id` supplied does not propagate through to the results that we are getting; which are consistently in line with the default/empty scenarios.

**Comment by noracato** [comment]
I checked it and indeed the module does noet seem to be making a copy of II3050, but instead creates a blank scenario where the inputs are then set on. When I do the exact same 'create a copy' request to ETEngine from a separate script it is working fine, so I suspect a nasty typo somewhere in the `ETM-HOLON` module. I'll be hunting!

**Comment by thesethtruth** [comment]
> I checked it and indeed the module does noet seem to be making a copy of II3050, but instead creates a blank scenario where the inputs are then set on. When I do the exact same 'create a copy' request to ETEngine from a separate script it is working fine, so I suspect a nasty typo somewhere in the `ETM-HOLON` module. I'll be hunting!

Awesome, after some hunting and manually querying on the side I came to the same conclusion. Good luck on the hunt! 🏹

**Comment by thesethtruth** [comment]
Notes from a convo with Peter:
financieel individueel - nodal pricing - day ahead - alleen batterij reageert daarop
	In actor contract aanmaken
	In gridconnection grid battery charging mode op price zetten
	Die gridconnection moet een battery asset hebben

financieel gezamelijke - nodal pricing - day ahead - alleen batterij reageert
	Gridcon met grid battery die energy holon is
	Gridcon mode price

**Comment by thesethtruth** [comment]
closes #208

**Comment by thesethtruth** [comment]
Tests failing on `match` switch statement because python 3.9. Can be converted to `elif`.

**Review by mattijsstam — APPROVED** [review]

**Pull request merged**
